---
- name: Gather groups to be created from users variables
  set_fact:
    users_groups: "{{ users_groups + [ item.1 ] }}"
  loop: "{{ users | subelements('groups') | list }}"
  when: users is defined
  vars:
    users_groups: []

- name: Add groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ users_groups }}"
  when: users_groups is defined
